version: '3'

services:
  postgres:
    image: 'postgres:10.1'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/chatbot'
    environment:
      - LANG=C.UTF-8

volumes:
  postgres:
